#!/bin/bash

find vendor -name ".git*" -type d | while read i
do
    if [[ -d $i ]]; then
        directory=`dirname $i`
        rm -fR $i
        git rm -r --cached $directory > /dev/null 2>&1
        git add $directory > /dev/null 2>&1
    fi
done