#!/bin/sh

directory_inspecao='/l/fnt/INSPECAO_CHAMADOS'
actual_directory=$(dirname "$(pwd)")

if [ $actual_directory = $directory_inspecao ]; then
    echo
    echo "****************************************************************************"
    echo "*                                                                          *"
    echo "*   PUSH IS NOT ALLOWED. THIS DIRECTORY IS ONLY FOR INSPECTION ANALISYS.   *"
    echo "*                                                                          *"
    echo "****************************************************************************"
    echo
    exit 1
else
    exit 0
fi